### ISSUE TITLE
BUG: Keyboard Shortcuts and Window Manager Keybindings won't *visually* change

### ISSUE THREAD

**Issue by TActually** [rhino-linux/unicorn#27] opened 2023-08-20 15:05 UTC
**Rhino Linux Version:**
2023.1

**Platform:**
VM (virt-manager/Qemu/kvm) running on AMD Ryzen 5 3600
Passed through 3 cores, 2 threads each.
50GB qcow 2 drive
passed through 16gb of Ram.
virtio for video/sound/controllers

**Describe the bug**
Unable to remove shortcuts or WM keybindings.
I can make changes to both, but they will not be reflected, visually.
I can add new shortcuts and they show visually in the keyboard settings.
If I add a WM keybinding, it will still show as blank, but the keybinding will work.
For example, I want to set the "Tile window to the left" keybinding to SuperL + Left. Currently it is set as SuperL + Kp Left, which I'm not sure what the "Kp" is. I click edit, I get the dialog box for setting the shortcut, the dialog responds to my key presses, then exits (which is normal). But back on the Window Manager Settings window, nothing has changed. However, actually pressing SuperL + Left actually works.

In the Keyboard shortcuts, I get the same exact result. Further more, when I tried to delete the default shortcut for "orca" which is not actually installed, it did not remove, but duplicated itself (visually).  However, I was able to add a new shortcut for an application I installed.

**To Reproduce**
1. Go to Window Manager Settings
2. Click on  "Keyboard"
3. Scroll down to 'Tile window to the left'
4. Double click it to get the 'Window Manager Action Shortcut' dialogue box.
5. Press the desired shortcut keys (ie; SuperL + Left).
6. Observe the Window Manager keybinding has not changed.
7. But, if you try the new shortcut you just set, it works.

**Expected behavior**
The keybinding change should be reflected in the settings window, instantly.

**Screenshots**

**Additional context**
I have an arch install with XFCE and I'm able to freely modify the shortcuts there. 
I think this is the same bug/problem with plank not respecting user setttings.

**Comment by ajstrongdev** [comment] 2023-08-20 18:46
Have you made any modifications to Unicorn is any way shape or form @TActually

**Comment by ajstrongdev** [comment] 2023-08-20 18:50
Looking at your messages on Discord you're still using xfwm4, can you provide some screenshots or a video of what is occuring?

**Comment by TActually** [comment] 2023-08-20 20:30
Hi AJ, wouldn't you know it, some of the changes started working when I took a video.
It's still a little screwy, as you'll see, but it's better now, then it was about 2 hours ago.
Weird, I haven't done rpk update -y, so not sure why the issue is fluctuating.

https://github.com/rhino-linux/unicorn/assets/59190173/0d816bdb-94ee-464d-b62b-954f32000135

**Comment by ajstrongdev** [comment] 2023-08-20 20:34
@oklopfer can you confirm whether this is an XFCE or Unicorn issue 🙏

**Comment by markob94** [comment] 2023-08-21 18:18
I just wanted to report the same bug. Clean install, nothing changed. And have the same bug

**Comment by oklopfer** [comment] 2023-08-21 21:11
@markob94 @TActually @ajstrongdev Yes, I can confirm this is an upstream XFCE issue, not a unicorn specific issue.
References:
https://forum.xfce.org/viewtopic.php?id=15542
https://forum.xfce.org/viewtopic.php?id=16521
https://forum.xfce.org/viewtopic.php?id=16842

**Comment by ajstrongdev** [comment] 2023-08-22 16:03
Closing due to this being an upstream XFCE issue. If it persists please open a bug with XFCE.

**Closed by ajstrongdev** 2023-08-22 16:03 UTC
Labels: bug

**Comment by TActually** [comment] 2023-08-26 01:19
Will keep an eye on this. id 15542 is  2 years old (previous version of xfce) and from Arch. The other 2 listings are more relevant (1 ubuntu based and 1 debian), but neither has any listed resolution. I'm wondering if the issue will be resolved at the same time as the plank config over-right issue...? regardless, thanks for rounding up this info!!!
