### ISSUE TITLE
BUG: LightDM fails to start properly

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#22] opened 2023-08-19 09:36 UTC
**Describe the bug**
On some systems, lightdm appears to be failing to launch Unicorn properly.

**Expected behavior**
Unicorn launches from LightDM properly.

**Temporary fix:**
We are investigating a cause for this issue. If experiencing this issue, switch to a TTY, and type the following in your terminal:
`sudo systemctl stop lightdm && unicorn-session`

**Comment by ajstrongdev** [comment] 2023-08-22 09:29
@oklopfer any update?

**Comment by oklopfer** [comment] 2023-08-22 18:14
It seems like the issue might only exist on NVIDIA laptops @ajstrongdev so...

**Comment by ajstrongdev** [comment] 2023-08-23 09:51
@oklopfer Right, once users have ran `sudo systemctl stop lightdm && unicorn-session` once does the issue persist, or do they only need to run that command once?

**Comment by oklopfer** [comment] 2023-08-23 16:24
> @oklopfer Right, once users have ran `sudo systemctl stop lightdm && unicorn-session` once does the issue persist, or do they only need to run that command once?

Remember earlier when I said I was gunna fall asleep but please comment here that the issue is `xserver-xorg-video-vesa xserver-xorg-video-fbdev` being missing, which I should add as unicorn deps

**Comment by pafranklin77** [comment] 2023-08-23 16:51
Having the same issue with a Lenovo using intel iRISxe graphics.

**Comment by oklopfer** [comment] 2023-08-24 00:09
> Remember earlier when I said I was gunna fall asleep but please comment here that the issue is `xserver-xorg-video-vesa xserver-xorg-video-fbdev` being missing, which I should add as unicorn deps

Based on https://wiki.ubuntu.com/X/Troubleshooting/VideoDriverDetection, this definitely was the issue. Closing up

**Closed by oklopfer** 2023-08-24 00:09 UTC
Labels: bug
